language: d

install:
    - sudo apt-get update -q
    - sudo apt-get install -y libxrandr-dev
matrix:
    allow_failures:
        - d: dmd-2.065.0
        - d: gdc-4.8.2
        - d: ldc-0.15.0-beta1
    include:
        - d: dmd-2.066.1
        - d: dmd-2.065.0
        - d: gdc-4.8.2
        - 
            d: ldc-0.15.0-beta1
            install:
                - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
                - sudo apt-get update -q
                - sudo apt-get install libstdc++6
                - ldc2 --version
script: dub build de_window:test --compiler=${DC}

notifications:
    webhooks:
        urls:
            - https://webhooks.gitter.im/e/6f57c4c76d7bfed91a29
        on_success: change  # options: [always|never|change] default: always
        on_failure: always  # options: [always|never|change] default: always
        on_start: false     # default: false