language: d
install:
    - sudo apt-get update -q
    - sudo apt-get install -y libxrandr-dev
matrix:
    allow_failures:
        # dmd FE 2.065
        - d: dmd-2.065.0
        - d: gdc-4.8.2
        - d: ldc-0.14.0
    include:
        - d: dmd-2.066.1
        - d: dmd-2.065.0
        - d: gdc-4.8.2
        - d: ldc-0.15.1
        - d: ldc-0.14.0
    install:
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get update -q
        - sudo apt-get install libstdc++6
        - ldc2 --version
script: dub build de_window:test --compiler=${DC}
