language: d

install:
    - sudo apt-get update
    - sudo apt-get install libxrandr-dev libstdc++6
matrix:
    allow_failures:
        - d: dmd-2.065.0
        - d: gdc-4.8.2
        - d: ldc-0.15.0-beta1
    include:
        - d: dmd-2.066.1
        - d: dmd-2.065.0
        - d: gdc-4.8.2
        - d: ldc-0.15.0-beta1
script: dub build de_window:test --compiler=${DC}