#define _MMINTRIN_H_INCLUDED 
#define _XMMINTRIN_H_INCLUDED 
#define _EMMINTRIN_H_INCLUDED 
#define _PMMINTRIN_H_INCLUDED 
#define _TMMINTRIN_H_INCLUDED 
#define _AMMINTRIN_H_INCLUDED 
#define _SMMINTRIN_H_INCLUDED 
#define _WMMINTRIN_H_INCLUDED 
#define _IMMINTRIN_H_INCLUDED 
#define _MM3DNOW_H_INCLUDED 
#define _FMA4INTRIN_H_INCLUDED 
#define _XOPMMINTRIN_H_INCLUDED 
#define _LWPINTRIN_H_INCLUDED 
#define _BMIINTRIN_H_INCLUDED 
#define _BMI2INTRIN_H_INCLUDED 
#define _TBMINTRIN_H_INCLUDED 
#define _LZCNTINTRIN_H_INCLUDED
#define _POPCNTINTRIN_H_INCLUDED

#define _X86INTRIN_H_INCLUDED 

#define __INTRIN_H_

#define _INC_EXCPT 

#include <_mingw.h>
#undef __MINGW_INTRIN_INLINE 

typedef char *  va_list;

#include <windows.h>